Chuvash_Workout/urls.py
from Chuvash_Workout import views
from django.urls import path


urlpatterns = [
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
    path('programs/', views.programs, name= 'programs'),
    path('review/', views.review, name= 'review'),
    path('programs/<slug:slug_id>/', views.programs_slug, name= 'programs_more'),
    path("profile/" ,views.profile, name='profile'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from users import views
from django.urls import path, reverse_lazy

from users.views import MyPasswordChangeView

app_name = 'users'
urlpatterns = [

    path('login/',views.Login_auth.as_view(), name= 'login'),
    path("register/" ,views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
    # path("login/register/",views.register, name='register'),
    path('password-change/',MyPasswordChangeView.as_view() , name='password_change'),
    path('password-change/done/',PasswordChangeDoneView.as_view(template_name='Chuvash_Workout/password_change_done.html'), name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(template_name='Chuvash_Workout/password_reset_form.html',
    email_template_name='Chuvash_Workout/password_reset_email.html',
 success_url=reverse_lazy('users:password_reset_done')                                                  ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='Chuvash_Workout/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='Chuvash_Workout/password_reset_confirm.html',
     success_url=reverse_lazy('users:password_reset_complete') ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view
    (template_name='Chuvash_Workout/password_reset_complete.html'),
         name='password_reset_complete' ),
    path('update-profile/<int:pk>', views.update_pro, name='update_profile')
]

workout_21/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Chuvash_Workout.views import page_not_found, permission_denied
from workout_21 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Chuvash_Workout.urls')),
    path('users/', include('users.urls', namespace='users'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Моя панель администирования'
admin.site.index_title = 'Моя панель тоже'

handler404 = page_not_found
handler403 = permission_denied

Chuvash_Workout/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from workout_21 import settings


# Create your models here.
# class workout_images(models.Model):
#     title =models.CharField(max_length=100)
#     cover = models.ImageField(upload_to='images/')
#     workout_images = models.FileField


class training(models.Model):
    objects = True
    name = models.CharField(max_length=250, db_index=True, unique=True, verbose_name='Заголовок')
    content = models.CharField(max_length=500, verbose_name= 'Основной контент')
    free = models.IntegerField(verbose_name='Доступ')
    slug = models.SlugField(max_length=250,unique=True, db_index=True,verbose_name= "Отображение url" )
    main_description = models.CharField(blank=True,default='',db_index=True, null=True,verbose_name= "Индивидуальный основной контент",max_length=500 )
    description1= models.CharField(blank=True,default='',db_index=True, null=True,verbose_name= "Поле параграфа 1",max_length=500)
    description2 = models.CharField(blank=True,default='',db_index=True, null=True,verbose_name= "Поле параграфа 2",max_length=500)
    class Meta:
        verbose_name = 'Программы тренировок'
        verbose_name_plural = 'Программы тренировок'
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return self.slug


class data_people(models.Model):
    objects = None
    name = models.CharField(max_length=250, verbose_name='Имя')
    surname = models.CharField(max_length=250, verbose_name='Фамилия')
    logins = models.CharField(max_length=250, verbose_name='Логин')
    passwords = models.CharField(max_length=250, verbose_name='Пароль')
    gender = models.SlugField(max_length=250, verbose_name='Пароль')
    def __str__(self):
        return self.name

class Reviews(models.Model):
    objects = None
    name = models.CharField(max_length=250,verbose_name='Имя отправителя',default='user')
    reviews = models.CharField(max_length=250, null=False, verbose_name='Отзыв')
    class Meta:
        verbose_name = 'Отзывы участников'
        verbose_name_plural = 'Отзывы участников'
    def __str__(self):
        return self.name



# Create your models here.
# class AddUsers(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='add', )
#     photos = models.CharField(max_length=255, null=True,verbose_name='photo')
#     data_birth = models.CharField(max_length=255, verbose_name='birth')
#     def __str__(self):
#         return self.user
#return reverse('programs', kwargs={'slug_id':self.slug})
#from Chuvash_Workout.models import programs
#python manage.py makemigrations
#python manage.py migrate
class MyUsers(models.Model):
    objects = None
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='add')
    photo = models.ImageField(verbose_name='Фотография', upload_to='photos/%Y/%m/%d',default=None,)
    date_bitrh = models.DateTimeField(verbose_name='Дата рождения')
    class Meta:
        verbose_name = 'Доп данные для User'
        verbose_name_plural = 'Доп данные для User'


def content_file_name(instance, filename):
    return '/'.join(['photos/%Y/%m/%d', instance.user.username, filename])

Chuvash_Workout/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible

from .models import data_people
from django.core.validators import MinLengthValidator,MaxLengthValidator

@deconstructible
class MyValidator():
    ALLOWED_CHARS = 'йцукенгшщзхъфывапролджэячсмитьбю'
    code = 'russian'
    def __init__(self, message = None):
        self.message= message if message else 'У нас только маленькие буквы русского алфавита'
    def __call__(self, value, *args, **kwargs):
        if not (set(value)) <= set(self.ALLOWED_CHARS):
            raise ValidationError(self.message, code=self.code)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

from Chuvash_Workout.forms import MyValidator
from Chuvash_Workout.models import MyUsers


class Autoriz(forms.Form):
    username = forms.CharField(max_length=255, label='Логин')
    password = forms.CharField(max_length=255, label='Пароль')

class classAutoriz(AuthenticationForm):
    username = forms.CharField(max_length=255, label='Логин',widget=forms.TextInput(attrs={'class':'form-input'}))
    password = forms.CharField(max_length=255, label='Пароль',widget=forms.PasswordInput(attrs={'class':'form-input'}))
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']
class Register2(forms.Form):
    gender_choise = (
        ('1', 'man'),
        ('2', 'woman')
    )
    name = forms.CharField(max_length=255, label='имя', min_length=5,validators=[MyValidator()],
                           error_messages={
                               'min_lenth': "слишком короткий заголовок",
                               'required':'Поле должно быть заполнено'},

                           )
    surname = forms.CharField(max_length=255, label='фамилия' ,
                              validators=[MinLengthValidator(5, message='Мин 5 сим'),MyValidator()])
    logins = forms.CharField(max_length=255,  label='логин')
    passwords = forms.CharField(max_length=255, label='пароль')
    gender = forms.ChoiceField(choices=gender_choise)


class Register(UserCreationForm):
     username = forms.CharField(max_length=255, label='Логин', min_length=5,widget=forms.TextInput(attrs={'class':'form-input'}))
     password1 = forms.CharField(max_length=255, label='Пароль', min_length=5,widget=forms.PasswordInput(attrs={'class':'form-input',}))
     password2 = forms.CharField(max_length=255, label='Повтор пароля', min_length=5,widget=forms.PasswordInput(attrs={'class':'form-input',}))
     class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name','password1']
        labels = {
        'username':'Логин',
        'password1':'Пароль',
        'first_name':'Имя',
        'email':'E-mail'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.TextInput(attrs={'class': 'form-input'})}


    # def clean_password2(self):
    #     cd = self.cleaned_data
    #     if cd['password'] != cd['password2']:
    #         raise forms.ValidationError('Пароли не совпадают')
    #      return cd['password']


     def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Еmail уже зарегестрирован')
        return email

class AddRegister(forms.ModelForm):
    class Meta:
        model = MyUsers
        fields = ['photo', 'date_bitrh']
        widgets = {
            'date_bitrh': forms.TextInput(attrs={'class': 'form-input'})}
        labels = {
            'date_bitrh': "Дата рождения",
            'photo': "Фото"
        }

class UpdateProfile(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'username': forms.TextInput(attrs={'class': 'form-input'})}


class MyformChangePass(PasswordChangeForm):
    old_password = forms.CharField(max_length=255, label='Старый пароль', min_length=5,
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(max_length=255, label='Новый пароль', min_length=5,
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(max_length=255, label='Подтверждение пароля', min_length=5,
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))

Chuvash_Workout/views.py
from bdb import foo

from django.conf.urls import handler404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseNotFound
from django.template.loader import render_to_string

# Create your views here.

from Chuvash_Workout.models import training, data_people, Reviews


def main(request):
    forms = Reviews.objects.all()

    return render(request,'Chuvash_Workout/mainn.html', {'form': forms})


def about(request):
    return render(request, 'Chuvash_Workout/about.html')
@login_required(login_url='users:login')
def programs(request):
    prog = training.objects.all
    #prog = get_object_or_404(training,slug=slug_id)
    data = {
        'title': prog,
    }
    return render(request, 'Chuvash_Workout/programs.html',data)
@permission_required(perm="Chuvash_Workout.view_training" ,raise_exception=True)
def programs_slug(request,slug_id):  ##настройка фронтенда
    prog = get_object_or_404(training,slug=slug_id)
    data = {
        'title': prog,

    }
    return render(request,'Chuvash_Workout/programs_base.html',data )










@login_required(login_url='users:login')
def profile(request):
    form = get_user_model
    return render(request, "Chuvash_Workout/profile.html", {'form':form})
@login_required(login_url='users:login')

def review(request):
    if request.method == 'POST':
        form = Reviews(request.POST)
        Reviews.objects.create(reviews=request.POST.get('reviews'))
    else:
        form = Reviews()
    listt = Reviews.objects.all()
    paginaror = Paginator(listt,3)
    page_number = request.GET.get('page')
    page_obj = paginaror.get_page(page_number)
    return render(request, 'Chuvash_Workout/review.html',{'page_obj':page_obj})





def page_not_found(request, exception):
    return HttpResponseNotFound("<h1>Извини брат, но страница не найдена<h1>")


def permission_denied(request,exception,template_name='Chuvash_Workout/403.html'):
    return render(request,template_name)

Chuvash_Workout/templates/Chuvash_Workout/login.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<head>
   <link rel="stylesheet" href="{% static 'Chuvash_Workout/CSS/login.css' %}">
</head>

    <div class="body">

    <div class="signin">
      <div class="content">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token%}
         <input type="hidden" name="next" value="{{next}}">
         <div class="form-error">{{form.non_field_errors}}</div>
          <h2>Вход</h2>
            {% for i in form %}
              <div class="input_box">
              <p><label  class="form-label" for="{{i.id_for_label}}">{{i.label}}</label>{{i}}</p>
              <div class="form-error">{{ i.errors }}</div>
          </div>
            {% endfor %}

          <div class="links">
            <a href="../register">Регистрация</a>
            <a href="{% url 'users:password_reset'%}">Забыли пароль</a>
          </div>
          <div class="button_block">
            <button type="submit" name="enter">Войти</button>
          </div>
          </form>
      </div>
    </div>

    </div>

{% endblock %}

Chuvash_Workout/templates/Chuvash_Workout/mainn.html
{% extends 'base.html' %}
{%load static%}
{% block content%}
<div class="back-image"></div>
<head>
      <link rel="stylesheet" href="{% static 'Chuvash_Workout/CSS/main.css' %}">

</head>
<div class="cont_main_iname">
<div class="back-image"></div>
<div class="content_main">
  <h1 class="main_title">Workout тренировки</h1>
  <ul class ='main_ul'>
    <li class="main_li">Без железа</li>
    <li class="main_li">С собственным весом</li>
    <li class="main_li">В любом месте</li>
    <li class="main_li">В любое время</li>
  </ul>
  <div class="main_button">
      <a href="#programs"><button type="reset" name="button" class="button">Программы</button></a>
      <div class="arrow"></div>
  </div>

</div>
</div>



<div class="programs"id=programs>
  <div class="base prog " id=programs1>
    <div class="prog2 left_prog">   <div class="image_prog prog3"><img class="img_programs" src="{% static 'Chuvash_Workout/images/base.jpg' %}" alt="Тренировка базы"></div>
      <div class="prog3"> <button type='submit' name="buy_button">Купить</button>
      </div></div>
    <div class="content prog2 right_prog">
      <div class="prog_title">Тренировка базы</div>
      <div class="prog_paragrath">Хочешь прокачать свое тело используя пол, турник и брусья? Тогда эта программа тебе подходит. 30 минутная тренировка, прокачка всех целевых мыщц, хорошое настроение тебе обеспечено</div>
    </div>

  </div>
  <div class="static prog"id=programs2>
    <div class="left_prog prog2">  <div class="image_prog prog3 "><img class="static_image img_programs" src="{% static 'Chuvash_Workout/images/static.jpg' %}" alt="Тренировка Статики"></div>
      <div class="prog3"> <button type='submit' name="buy_button">Купить</button>
      </div></div>
      <div class="content prog2 right_prog">
        <div class="prog_title">Тренировка Статики</div>
        <div class="prog_paragrath">Хочешь научиться владеть стойкой на руках? А тем более отжиматься в ней, то тебе точно сюда. Мощные плечи, руки тебе обеспечены</div>
      </div>
  </div>
  <div class="dinamic prog"id=programs3>
    <div class="left_prog prog2">  <div class="image_prog prog3"><img class="img_programs" src="{% static 'Chuvash_Workout/images/dinamic.jpg' %}" alt="Тренировка Динамики"></div>
      <div class="prog3"> <button type='submit' name="buy_button">Купить</button>
      </div></div>
      <div class="content prog2 right_prog">
        <div class="prog_title">Тренировка Динамики</div>
        <div class="prog_paragrath">Хочешь наконец выучить что-нибудь интереснее топорика, то тебе подойдет этот курс. Здесь ты научишься базвоым динамическим элементам, в том числе и солнышко.</div>
      </div>
  </div>

  <div class="coming_soon prog"id=programs4>
    <div class="left_prog prog2">  <div class="image_prog prog3"><img class="img_programs" src="{% static 'Chuvash_Workout/images/coming_soon.webp' %}" alt="Скоро..."></div>
      <div class="prog3"> <button type='submit' name="buy_button">Купить</button>
      </div></div>
      <div class="content prog2 right_prog">
        <div class="prog_title">Coming soon</div>
        <div class="prog_paragrath">Скоро в продаже</div>
      </div>
  </div>
</div>

<div class ='cont_youtube'>
  <h1>Бесплатная вводная тренировка</h1>
<div class="youtube">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/SUVKvkf1NSE?si=VILbUDx1NBaN-ni0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
  </div>

<div class="FAQ">
  <h1 class="FAQh" id="questions">Частые вопросы</h1>
  <details class="details" >
  <summary>Стоит ли покупать курсы с 0-ой подготовкой? </summary>
  <p class="faq_content">Тренировка базы и Статики да, стоит. По началу будет тяжело, главное не сдававться.</p>
  </details>
  <details >
    <summary>Сколько длятся курсы по времени</summary>
    <p class="faq_content"> У них нет точного ограничения по времени. Вы можете прогрессировать как пару месяцев, так и пару лет. Все зависит от желания.</p>
  </details>
  <details >
    <summary>Какие элементы я изучу по - Тренировка Статики? </summary>
    <p class="faq_content">На данный момент с помощью данного курса вы сможете изучить Идеальную стойку на руках и ее вариации. И отжимания в стойке.</p>
  </details>
  <details >
    <summary>Что делать если нет прогресса? </summary>
    <p class="faq_content">Если вы вдруг замечаете такое, то на это есть несколько факторов: сон, питание, стресс, процент кислорода в крови... Вы всегда можете проконсультироваться со мной, мои контакты указаны а шапке и в нижней части экрана</p>
  </details>
</div>



{% endblock %}

Chuvash_Workout/templates/Chuvash_Workout/password_change_done.html
{%extends 'base.html' %}
{% block content %}
<h1>Вы успешно сменили пароль) <a href="{% url 'users:login' %}">Заново авторизоваться</a></h1>

{% endblock%}

Chuvash_Workout/templates/Chuvash_Workout/password_change_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'Chuvash_Workout/CSS/profile.css' %}">
    <title>Профиль</title>
  </head>

<div class="body">
  <div class="image_block">
    <div class="image_block2"> <img src="{{user.add.photo.url}}" alt="profile_photo"></div>
    <div class="image_content">
      <div class="image_login">{{user}}</div>
      <div class="email_login">{{user.email}}</div>
    </div>
  </div>
  <div class="profile_block">
    <div class="content_form">
      <div class="input_form" style="height:auto">
          <form action="">
              {% csrf_token %}
        {% for i in form%}
        <div class="form1 form">
           <div class="label_div"><label  class="" for="{{i.id_for_label}}">{{i.label}}</label></div>
   <div class="input_div">{{i}}</div>
    <div class="form-error">{{ i.errors }}</div>
          </div>
          {% endfor %}

        </form>
      </div>

      <div class="button_form">
        <a href="{% url 'users:update_profile' user.id %}"><button type='submit' name="save">Изменить</button></a>
        <a href="{%url 'users:password_change'%}"><button type='submit' name="save">Сменить пароль</button></a>
      </div>
    </div>
  </div>
  <div class="dop_block">


    <div class="dop_content_block">
      <div class="doph"> Контактная информация</div>
      <div class="dop_contact"></div>
    </div>
  </div>
</div>
{% endblock %}
}

Chuvash_Workout/templates/Chuvash_Workout/password_reset_complete.html
{%extends 'base.html' %}
{% block content %}
<h2>Пароль был успшено изменен! </h2>
<p>Вы можете перейти обратно на <a href="{% url 'main' %}">Главную страницу</a></p>
{% endblock %}

Chuvash_Workout/templates/Chuvash_Workout/password_reset_confirm.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" href="{% static "admin/css/forms.css" %}">{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
&rsaquo; {% translate 'Password reset confirmation' %}
</div>
{% endblock %}

{% block content %}

{% if validlink %}

<p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form method="post">{% csrf_token %}
  <fieldset class="module aligned">
    <input class="hidden" autocomplete="username" value="{{ form.user.get_username }}">
    <div class="form-row field-password1">
      {{ form.new_password1.errors }}
      <div class="flex-container">
        <label for="id_new_password1">{% translate 'New password:' %}</label>
        {{ form.new_password1 }}
      </div>
    </div>
    <div class="form-row field-password2">
      {{ form.new_password2.errors }}
      <div class="flex-container">
        <label for="id_new_password2">{% translate 'Confirm password:' %}</label>
        {{ form.new_password2 }}
      </div>
    </div>
  </fieldset>
  <div class="submit-row">
    <input type="submit" value="{% translate 'Change my password' %}">
  </div>
</form>

{% else %}

<p>{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

Chuvash_Workout/templates/Chuvash_Workout/password_reset_done.html
{%extends 'base.html'%}
{% load i18n %}
{% block content%}
<h1>Перейди по ссылке для сброса пароля. Возмоожно тебе стоит проверить папку со спамом</h1>
<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
{%endblock%}

Chuvash_Workout/templates/Chuvash_Workout/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

Chuvash_Workout/templates/Chuvash_Workout/password_reset_form.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<head>
   <link rel="stylesheet" href="{% static 'Chuvash_Workout/CSS/login.css' %}">
</head>

    <div class="body">

    <div class="signin">
      <div class="content">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token%}
         <input type="hidden" name="next" value="{{next}}">
         <div class="form-error">{{form.non_field_errors}}</div>
          <h2>Восстановление</h2>
            {% for i in form %}
              <div class="input_box">
              <p><label  class="form-label" for="{{i.id_for_label}}">{{i.label}}</label>{{i}}</p>
              <div class="form-error">{{ i.errors }}</div>
          </div>
            {% endfor %}

          <div class="button_block">
            <button type="submit" name="enter">Отправить </button>
          </div>
          </form>
      </div>
    </div>

    </div>

{% endblock %}

Chuvash_Workout/templates/Chuvash_Workout/programs.html
{% extends 'base.html'%}
{% block content %}
<body>
<h1>Программы тренировок:</h1>
<h2>Данные программы подаразумевают: </h2>
{%for i in title%}
<ul>
<!--   <li> <a href="{{i}}/">{{i}}</a></li> -->
    <li> <a href="{{ i.get_absolute_url}}/">{{i}}</a></li>
</ul>
<p>{{i.content}}</p>
{%endfor%}
 {% endblock%}

Chuvash_Workout/templates/Chuvash_Workout/programs_base.html
{% extends 'base.html'%}

{% block content %}


<h1></h1>
<!--{% if title.slug == 'base' or title.slug == 'static' or title.slug == 'dynamic' or title.slug == 'standhand' %}-->
<h1>Здесь будут находится базовые упражнения<h1>
    <h1>{{title}} - Базовые тренировки</h1>
    <h3>В данной тренировке будут задействованы упражнения: {{title.content}}</h3>
<h3>{{title.main_description}}</h3>
<p><strong>Уровень Beginner: </strong>{{title.description1}}</p>
<p><strong>Уровень Advanced: </strong>{{title.description2}}</p>


{%endif%}


{% endblock %}

Chuvash_Workout/templates/Chuvash_Workout/register.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<head>
   <link rel="stylesheet" href="{% static 'Chuvash_Workout/CSS/login.css' %}">
    <style> .body{transform: scale(0.8); .signin{margin:0;}</style>
</head>

    <div class="body">

    <div class="signin">
      <div class="content">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token%}
         <input type="hidden" name="next" value="{{next}}">
         <div class="form-error">{{form.non_field_errors}}</div>
          <h2>Регистрация</h2>
            {% for i in form %}
              <div class="input_box">
              <p><label  class="form-label" for="{{i.id_for_label}}">{{i.label}}</label>{{i}}</p>
              <div class="form-error">{{ i.errors }}</div>
          </div>
            {% endfor %}
            {% for i in form2 %}
              <div class="input_box">
              <p><label  class="form-label" for="{{i.id_for_label}}">{{i.label}}</label>{{i}}</p>
              <div class="form-error">{{ i.errors }}</div>
          </div>
            {% endfor %}


          <div class="button_block">
            <button type="submit" name="enter">Регистрация</button>
          </div>
          </form>
      </div>
    </div>

    </div>

{% endblock %}

Chuvash_Workout/templates/Chuvash_Workout/register_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Добро пожаловать! Вы успешно зарегестрировались в систему</h1>
<p></p>
</body>
</html>

Chuvash_Workout/templates/Chuvash_Workout/review.html
{% extends 'base.html' %}
{% block content %}

<h1>Отзывы</h1>
<section class="reviews">
{% for i in page_obj%}  
        <div class="reviews__element">
            <div class="reviews__element-title">
                <div class="h3">{{i}}</div>
            </div>
            <div class="reviews__element-description">
                <p>{{i.reviews}}</p>
            </div>
        </div>

{% endfor %}
</section>

<div class="pagination">
    {% for i in page_obj.paginator.page_range %}
<ul class="pagination-container">
    <li class="pagination-element"><a href="?page={{i}}">{{i}}</a></li>
</ul>
    {%endfor%}
</div>

<!-- если есть права на добавление контента -->
{% if perms.Chuvash_Workout.add_reviews %} 
<h1><label for="rev" class="rew">Напишите свой отзыв</label></h1>
<div class="main-info" id="review"> 
    <form class="form-review" method="post">
        {% csrf_token %}
        
        <textarea name="reviews" id="rev" cols="50" rows="10" placeholder="Мне нравится..." ></textarea>
        <button type="submit">Отправить</button>
        
    </form>
</div>
  {% endif %}
{% endblock %}